Controllers/ShaperController.cs
using System;
using System.Web.Mvc;
using Orchard;
using Orchard.DisplayManagement;
using Orchard.Themes;


namespace Hazza.ShapeField.Controllers
{
    public class ShaperController : Controller
    {
        private readonly IShapeDisplay shapeDisplay;

        public ShaperController(IShapeFactory shapeFactory, IShapeDisplay shapeDisplay)
        {
            Shape = shapeFactory;
            this.shapeDisplay = shapeDisplay;
        }

        dynamic Shape { get; set; }

        // for some reason this doesn't work, in the "callsite" bit returns the shape as null. works fine in other places...
        public ActionResult TestShape(string shape)
        {
            var test = Shape.Create(shape);
            var html = shapeDisplay.Display(shape);
            return Json(html, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/EditorTemplates/Fields/Shape.Edit.cshtml
@model Hazza.ShapeField.Fields.ShapeField

@{
    Script.Require("jQuery").AtFoot();
    var readUrl = Url.Action("TestShape", "Shaper", new { Area = "Hazza.ShapeField" });
}

<fieldset>
    @Html.LabelFor(m => m.Value, @T("Shape"))
    @Html.EditorFor(m => m.Value)
    <p class="hint">Name of the shape you want to display, beware that if this shape does not exist you will get an ugly yellow page of death</p>
</fieldset>

@* broken...for now
@using (Script.Foot()) {
    <script type="text/javascript">
        $(".pew").click(function() {
            $.getJSON('@readUrl', {
                    shape: "test"
                }).done( function(data) {
                $('#testy').html(data);
            });
        });
    </script>
}*@

Views/Fields/Shape.cshtml
@model dynamic

<div class="shape-@Model.ContentField.Value">
    @Display(Model.FieldShape)
</div>